// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAz48d9JimT7lqTLBTvtw4xNhfEJIEm4I',
    appId: '1:208562666884:web:c2fb5eb4da41e156e771d1',
    messagingSenderId: '208562666884',
    projectId: 'cassiere-7a631',
    authDomain: 'cassiere-7a631.firebaseapp.com',
    storageBucket: 'cassiere-7a631.appspot.com',
    measurementId: 'G-QXLEPMG9F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChVoc6efJ9N88kfnQhsJAmcX8bAfNTw-U',
    appId: '1:208562666884:android:87be376b33dcc97de771d1',
    messagingSenderId: '208562666884',
    projectId: 'cassiere-7a631',
    storageBucket: 'cassiere-7a631.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPWEgW5j72wrTh6ONbBpskDFislu4BC9A',
    appId: '1:208562666884:ios:b6c387a8bc7628d3e771d1',
    messagingSenderId: '208562666884',
    projectId: 'cassiere-7a631',
    storageBucket: 'cassiere-7a631.appspot.com',
    androidClientId: '208562666884-u248l4gsns9fof5629pse522ttcqcmku.apps.googleusercontent.com',
    iosClientId: '208562666884-q3cpua6v1mvi14tfeq9126kqi9ftpkh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cassiere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPWEgW5j72wrTh6ONbBpskDFislu4BC9A',
    appId: '1:208562666884:ios:b6c387a8bc7628d3e771d1',
    messagingSenderId: '208562666884',
    projectId: 'cassiere-7a631',
    storageBucket: 'cassiere-7a631.appspot.com',
    androidClientId: '208562666884-u248l4gsns9fof5629pse522ttcqcmku.apps.googleusercontent.com',
    iosClientId: '208562666884-q3cpua6v1mvi14tfeq9126kqi9ftpkh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cassiere',
  );
}
